### ISSUE TITLE
expose internal api

### ISSUE THREAD

**Issue by seriousManual** [linkedin/dustjs#349]
I'd like to propose the exposure of internal classes used by dust to render and compile templates.

For that we've got the following usecase:
A serverside renderservice is responsible for the compiling, caching and rendering of templates. We're planning to persist compiled templates to disk so that service startups can be much more performant.

There are two possibilities to compile a template:
````javascript
var template = 'hello {world}!';

var a = dust.compileFn(template, 'foo');
var b = dust.compile(template, 'bar');
````
The first method returns a function that can actually be invoked, the second returns a string that represents the body of the function that is referenced in the returnvalue of the first function:

dust.compileFn(...)
````javascript
function (context, callback) {
    var master = callback ? new Stub(callback) : new Stream();
    dust.nextTick(function() {
      tmpl(master.head, Context.wrap(context, name)).end();
    });
    return master;
  }
````

dust.compile(...)
````javascript
(function(){dust.register("bar",body_0);function body_0(chk,ctx){return chk.write("hello ").reference(ctx.get("world"),ctx,"h").write("!");}return body_0;})();
````

if we now take the output of the second function and save that to a file it is not possible to regain a executeable function without having access to the classes `Stub`, `Context` and `Stream`. These are hidden in the dust library. 
It would be a easy thing to just say 
````javascript
var dust = {
  ...
  Stream: Stream,
  Stub: Stub,
  Context: Context,
  ...
};
````

what do you think?

**Comment by sethkinast** [comment]
With #613 you can do:

    var tmpl = require('./compiled/tmpl.js')(dust);
    tmpl({ source: 'cake' }, function(err, out) {
      // out = 'some cake'
    });

Where `tmpl.js` was created by setting `dust.config.cjs = true` and then running `dust.compile`, or running `dustc --cjs`.

The reasons that you still have to hydrate the template with dust (rather than the template doing `require('dustjs-linkedin')`, e.g., are:

  * Would have to support people using different dust modules, e.g. `dustjs-helpers`, `dustjs-secure-filters`
  * If there were a method to somehow inject these into the compiled template (gross), the template then becomes less portable.

It's much easier for you to set up a dust the way you like and inject it-- you could even write a little helper function to do this for you.

    function requireTemplate(path) {
      var dust = require('dustjs-helpers');
      dust.helpers.foobar = myHelper;
      return require(path)(dust);
    }
