### ISSUE TITLE
caching is unavoidable

### ISSUE THREAD

**Issue by tunderdomb** [linkedin/dustjs#451]
`dust.load` does this: 

          if (!dust.cache[name]) {
            dust.loadSource(dust.compile(src, name))
          }
          else {
            dust.cache[name](chunk, context).end();
          }

but it should be like this: 

        if ( dust.isCachingDisabled ) {
          dust.loadSource(dust.compile(src, name))(chunk, context).end();
        }
        else {
          if (!dust.cache[name]) {
            dust.loadSource(dust.compile(src, name))
          }
          else {
            dust.cache[name](chunk, context).end();
          }
        }

so caching can truly be disabled. 
Because even if you overwrite `dust.register`, a compiled template calls it for naught. 
The callback chain looks something like this:

    dust.compile -> dust.loadSource -> eval -> dust.register -> ???

Right now dust doesn't care if you want to avoid caching. It's pretty much mandatory now.

**Comment by sethkinast** [comment]
In #613 you can set `dust.config.cache = false` and caching will be disabled.

This means that `dust.loadSource` basically has no effect.

You will either have to have a `dust.onLoad` function defined to allow Dust to load templates, or you can pass a compiled function directly to `dust.render` (instead of the template's name).

**Comment by tunderdomb** [comment]
This looks wonderful, a lot of nice additions too. Thank you for mentioning this!
