### ISSUE TITLE
Problems with .Net minification system

### ISSUE THREAD

**Issue by killanaca** [linkedin/dustjs#500]
Hi
there are some problems with the new version ( 2.4.1 ) and the .net minification system (System.Web.Optimization). When i use it in production (with the files minified by the .net library) the javascript console gives me an error
"Uncaught TypeError: Cannot set property 'dust' of undefined "
With version 2.3.3 all works like a charm.

Any idea?

**Comment by boneskull** [comment]
I still have this issue in 2.5.1

**Comment by sethkinast** [comment]
Let's get this fixed for 2.6.2.

This works because the IIFE invocation returns the default context of new functions, which is the global windowlike scope in Node and the global window scope in the browser.

When `lib/dust.js` is run directly, like `node lib/dust.js`, then everything also works as expected even if you just use `this`, because Node evaluates the entry point with `this` set to the windowlike.

**However**, when you `require('lib/dust.js')` like `server.js` does, Node evaluates `dust.js` with `this` set to an empty Object. I am not sure why this is, or how you can override the scope. So the IIFE was allowing us to get a windowlike scope.

I think the best fix is to drop `root` from any code that we expect to be run on both browser and server. `root` should only refer to the browser window.
