### ISSUE TITLE
When should parameter contexts be evaluated?

### ISSUE THREAD

**Issue by sethkinast** [linkedin/dustjs#528]
Consider the example:

    {#foo param="I come from {tap}"}
      {param} {! I come from inside foo !}
      {#bar}
        {param}{! I come from inside bar !}
      {/bar}
    {/foo}

    {
      "foo": true,
      "tap": "inside foo",
      "bar": {
        "tap": "inside bar"
      },
    }

Should parameter contexts be evaluated at parameter creation, or parameter usage?

**Comment by jimmyhchan** [comment]
Ouch!  I'm surprised by this, then again, maybe not that surprised at all.

(*Rereading this I'm not sure if this is true -- read with skepticism *)
One argument against evaluating at the point of instantiations is streaming. Parameters are basically mini templates and can modify the context. In streams, the data is not known until runtime and parameters *have to* be evaluated late, otherwise we would have to block/fork (execution) every time we see a block (partial or section) with a parameter.

(* I'd have to experiment with what this actually does. Seems like it'll be useful for streams, but it shouldn't necessarily be the default)


Seems there are two use cases: Pass by value vs. creating something akin to an anonymous function callable with the current context and scope

random thought: We can implement an IFFE syntax for functions passed by value
```
#foo param="I come from {tap}"()
```

**Comment by sethkinast** [comment]
Now that we have `context.resolve` this is not a problem for me.
