### ISSUE TITLE
HTML with no tabs

### ISSUE THREAD

**Issue by PaquitoSoft** [linkedin/dustjs#547]
Hello,
When I render a template (I use dust server-side), I would like the resulting HTML to have no tabs between tags.

Let's say I have this template:
```
<div class="people">
    {#people}
        <span>{fullName}</span>
    {/people}
</div>
```
The resulting HTML (using *dust.config.whitespace = false*) would be like this:
```
<div class=people">        <span>Han Solo</span>        <span>Luke Skywalker</span></div>
```

That's because web use tabs for indentation in our code and we'd prefer not to change that.

Is there anyway I can have no spaces between tags?
Something like this:
```
<div class=people"><span>Han Solo</span><span>Luke Skywalker</span></div>
```

Thanks!

**Comment by sethkinast** [comment]
The tabs should be stripped.

I put your example into http://linkedin.github.io/dustjs/test/test.html (making sure that I added tab characters, not spaces) and the output was as expected:

```
<div class="people"><span>Han Solo</span><span>Luke Skywalker</span></div>
```

Could you try to provide code that reproduces the issue? If there's a case where we aren't stripping tabs, we can fix it.

**Comment by PaquitoSoft** [comment]
Thanks for the info.
I will try to take an excerpt of my large templates.

**Comment by PaquitoSoft** [comment]
@sethkinast I found that there were some whitespaces after the *span* tag. There were no tabs so that was my mistake.
Anyway, I thought dust would strip whitespaces when using
```
dust.config.whitespace = false;
```

Thanks

**Comment by sethkinast** [comment]
With some exceptions, Dust won't strip whitespace within a "buffer"-- within a string that Dust sees as part of your content. For example, Dust won't strip out whitespace here:

    H   e   l   l   o

Because that string is viewed as a single unit.

So if you have some whitespace after a span tag:

    <span>Hello</span>_ _ _ _ _
                      ^ ^ ^ ^ ^

That whitespace looks like part of the preceding string, so Dust respects it.

**Comment by PaquitoSoft** [comment]
I'm sorry but I don't get it. If I have whitespaces before de open span tag, they are stripped; but they're not if they are after the closing span tag, even when the tag has been closed and there is no more *content* in that line...

**Comment by sethkinast** [comment]
OK, let's dive in deeper.

Here is the parsed **AST** (Abstract Syntax Tree) that Dust generates when compiling your template assuming some trailing space after the `</span>`. (Scroll down to see it.) Remember that if you have `dust.config.whitespace = false`, all nodes of type `format` will get blown away.

Do you notice something about the buffer containing your `</span>`? It has the extra whitespace! This means it won't get optimized away when the `format` nodes are removed.

Why is this? It's because when Dust matches a node, `format` nodes are defined as "a newline character plus some amount of whitespace". Because your `</span>` doesn't have a newline after it, the whitespace is treated as part of that buffer.

You didn't run into this case, but if you had something like `{#people}    <span>`, the leading whitespace wouldn't be stripped either, because it isn't preceded by a newline.

```
[
    "body", [
        "buffer",
        "<div class=\"people\">"
    ],
    [
        "format",
        "
        ",
        "    "
    ],
    [
        "#", [
            "key",
            "people"
        ],
        [
            "context"
        ],
        [
            "params"
        ],
        [
            "bodies", [
                "param", [
                    "literal",
                    "block"
                ],
                [
                    "body", [
                        "format",
                        "
                        ",
                        "        "
                    ],
                    [
                        "buffer",
                        "<span>"
                    ],
                    [
                        "reference", [
                            "key",
                            "fullName"
                        ],
                        [
                            "filters"
                        ]
                    ],
                    [
                        "buffer",
                        "</span>     ",
                    ],
                    [
                        "format",
                        "
                        ",
                        "    "
                    ]
                ]
            ]
        ]
    ],
    [
        "format",
        "
        ",
        ""
    ],
    [
        "buffer",
        "</div>"
    ]
]```
