### ISSUE TITLE
Secure or disable context helpers

### ISSUE THREAD

**Issue by felipegs** [linkedin/dustjs#662]
Hi,
Is there anyway to block context helpers or to secure it,  to prevent it from things like this:
Template
```
{#appStatusOK}
  Everything is awesome!
  {:gearsError}
    Gears are stopped! Status code: {gears.error}
  {:engineError}
    Engine is not running! Engine temperature: {engine.temperature}
  {:oilLevelError}
    Oil level is too low! Current level: {engine.oilLevel}
{/appStatusOK}
```
Data
```
{
  "gears": {
    "status": "OK",
    "error": false
  },
  "engine": {
    "status": "OK",
    "error": false,
    "oilLevel": 0.5,
    "temperature": 80
  },
  "appStatusOK": function(chunk, context, bodies, params) {
   while(true);
  }
}
```

**Comment by sethkinast** [comment]
When I was at Amazon, we used AWS Lambda (http://aws.amazon.com/lambda/)
and forcefully killed execution if rendering took too long. We had a use
case where we had to run untrusted helpers.

If you don't want to use helpers at all, you can run your context through
JSON.stringify:

    var safeContext = JSON.parse(JSON.stringify(unsafeContext));

And all the functions will be stripped out.

Because Node is single-threaded, there's no way to forcefully end execution
from within the same thread. You would need to spawn a separate process to
do your Dust rendering and kill it after a timeout.

See `cluster`: https://nodejs.org/api/cluster.html

On Tue, May 12, 2015 at 5:59 PM, Felipe Guimarães Santos <
notifications@github.com> wrote:

> Hi,
> Is there anyway to block context helpers or to secure it, to prevent it
> from things like this:
> Template
>
> {#appStatusOK}
>   Everything is awesome!
>   {:gearsError}
>     Gears are stopped! Status code: {gears.error}
>   {:engineError}
>     Engine is not running! Engine temperature: {engine.temperature}
>   {:oilLevelError}
>     Oil level is too low! Current level: {engine.oilLevel}
> {/appStatusOK}
>
> Data
>
> {
>   "gears": {
>     "status": "OK",
>     "error": false
>   },
>   "engine": {
>     "status": "OK",
>     "error": false,
>     "oilLevel": 0.5,
>     "temperature": 80
>   },
>   "appStatusOK": function(chunk, context, bodies, params) {
>    while(true);
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/dustjs/issues/662>.
>



-- 
Seth Kinast
http://sethkinast.com/

**Comment by felipegs** [comment]
Could be a solution, however it has a big overhead.
 Imagine if you have a big payload JSON.parse and JSON.stringfy may block event-loop of node.

**Comment by sethkinast** [comment]
Not as much as `while(true)` would block the loop ;)

Anyways, either you trust your context (in which case an evil function is a bug, not a vulnerability), or you don't trust it and you should preprocess it to strip out helpers.

You can preprocess any way you want-- you could loop over the context and check `typeof` to see if it's a function and remove it if you don't want to run `JSON.parse` (and if you're that concerned about the size of your object, check the size before parsing or something).

Or you can run in a protected context that you can kill, by forking a child.
