### ISSUE TITLE
Possible to call functions on object?

### ISSUE THREAD

**Issue by elliotlings** [linkedin/dustjs#675]
Is it possible to call a function on an object?

Would be really helpful :)

**Comment by sethkinast** [comment]
Do you mean http://www.dustjs.com/guides/context-helpers/ ?

**Comment by elliotlings** [comment]
```
res.stream('index', {
    "someObject": {
        getSomething: function() {
            return ...
        }
    }
});
```

```
{someObject.getSomething()}
```

**Comment by sethkinast** [comment]
Yes, just take off the parentheses and dust will invoke the function. Read
the above link for details.

**Comment by sethkinast** [comment]
And check out the examples on the page; you can edit them live and they'll
compile in real time.

**Comment by elliotlings** [comment]
Oh cool. Do method calls all get passed chunk, context, bodies, params arguments?

**Comment by sethkinast** [comment]
Yep!

**Comment by elliotlings** [comment]
Hmm ok. I'm trying to pass models into the views (I'm using this: http://bookshelfjs.org) but it's become a bit problematic calling methods on it such as related('...') which may sway me to another template language :/ Any suggestions?

**Comment by elliotlings** [comment]
I could do something like this http://stackoverflow.com/questions/24368464/call-function-from-dust-template but I'm not sure it's an elegant solution.

**Comment by sethkinast** [comment]
So Dust's position is that invoking methods with arguments is too much logic for your template. (If you want to really write Javascript in a template you should use something like EJS).

You have a couple Dustlike approaches. First, you can pass context variables that represent your desired data, rather than constructing it on the template. So something like this (using the Bookshelf example):

```
{
  "userPhoto": function(chunk, context, bodies, params) {
    var photoId = context.resolve(params.id);
    return new Photo({id: photoId}).fetch({
      withRelated: ['account']
    });
  }
}

and invoke it with

```
{#userPhoto id=userId}<img src="{.}" />{/userPhoto}
```

Or, if calling `.related` is something you do often, you could write a context helper to help you do this:

```
{
  "related": function(chunk, context, bodies, params) {
    var model = context.resolve(params.model);
    var related = context.resolve(params.related);

    return model.related(related);
}
```

And invoke it with

```
{#related model=myModel related="..." /}
```

It's hard to nail down something that exactly works for you; but the docs have a ton of examples.

**Comment by elliotlings** [comment]
That's great, thanks for your help. I shall have a play around and see if it works for what I need. I can see where you are coming from about calling JavaScript in your template is too much logic, how I avoided that I was unsure, thanks for offering some solutions :)

**Comment by sethkinast** [comment]
Ideally from the Dust point of view, each variable in your template is ready to output, so that Dust can just iterate over it. You can put functions that return arrays or Promises that resolve into arrays right into your context, rather than putting that logic in your template. So if you do all the resolution of related models beforehand, your template can be structured very cleanly.
