### ISSUE TITLE
CommonJS (--cjs) option does not handle partials well at all

### ISSUE THREAD

**Issue by kmudrick** [linkedin/dustjs#678]
If you compile templates with the --cjs option, which use partials, then I would expect that require()ing one of those templates would also pull in the partials as well.  That does not seem to be the case.

**Comment by sethkinast** [comment]
You'll need to define a `dust.onLoad` function to pull in partials, because Dust doesn't know how you expect your partials to be loaded. Maybe they're accessed over the network, or they're stored in a memory cache.

Take a look at the CommonJS example app: https://github.com/linkedin/dustjs/tree/master/examples/commonjs

In `requireTemplate.js`, a dust.onLoad function is defined to tell dust that we plan to load templates by `require`ing them from a `views` path. After that, you never have to `require` a template manually-- just call `dust.render`, and the template is automatically required!

**Comment by sethkinast** [comment]
Also see http://www.dustjs.com/guides/onload/

**Comment by kmudrick** [comment]
Thank you @sethkinast - this was helpful

**Comment by sethkinast** [comment]
Please let us know if we can improve the docs or help you out with your implementation. This is intended to be a very strong part of Dust.

I'll go ahead and close the issue but just reopen it and reply if you have follow-up questions.
