### ISSUE TITLE
False boolean value on context

### ISSUE THREAD

**Issue by diegossilveira** [linkedin/dustjs#684]
When there's a `false` boolean value on context, dust.js can't print it on rendered template.

Let the template be:

```javascript
{#object}str: {str}, num: {num}, bool: {bool}{/object}
```

And supplying this context:

```javascript
{
   object: {
      str: 'test',
      num: 2,
      bool: false
   }
}
```

The resulting template is rendered something like:

```javascript
str: test, num: 2, bool:
```

If the `bool`value is changed to `true`on context, the resulting template is rendered this way:

```jvascript
str: test, num: 2, bool: true
```

Is it expected or a bug?

**Comment by smfoote** [comment]
This seems like a bug to me. If a boolean `true` outputs the string `"true"`, then a boolean `false` should output the string `"false"`. Or they should both output nothing, though I prefer that they output the string version of themselves.

**Comment by sethkinast** [comment]
This has to do with Dust's logic for handling emptiness (which is not the same as falsiness as 0 is not empty); it's been this way since the akdubya dust days.

The rules for handling empty are:

  * empty arrays are empty
  * everything falsy except 0 is empty

Changing it in one place does introduce an inconsistency in the way Dust handles all other empties (which is not to print them, e.g. `null` doesn't get printed) and also makes handling `false` not work the same way everywhere. :/

If you need this behavior you can always do `{?foo}true{:else}false{/foo}` but I don't foresee this changing owing to consistency / backcompat.

**Comment by diegossilveira** [comment]
Thank you @smfoote and @sethkinast for the quick reply!

Actually I used an expression like this `{?foo}true{:else}false{/foo}` to solve my problem. I was just wondering if this could be fixed on Dust.js, but I can understand the compatibility arguments.
