### ISSUE TITLE
call userCan('edit data")  in DustJs

### ISSUE THREAD

**Issue by finfort** [linkedin/dustjs#714]
How I can call something like this in Dust?

    {@userCan permission="edit data"}
      <td><a href='/assets/edit/{.ID_ASSET}'>Edit</a></td>
      <td><a href='/assets/delete/{.ID_ASSET}'>Delete</a></td>
    {:else}
      Please log in.
    {/userCan}
Such helper didn't work properly

    dust.helpers.userCan = function(chunk, context, bodies, params) {
      var permission = context.resolve(params.permission);
      return userCan(permission);
    }

https://github.com/ForbesLindesay/connect-roles

    req.userCan(action) and req.userIs(action)

can and is are synonyms everywhere they appear.

These functions return true or false depending on whether the user has access.

e.g.

    app.get('/', function (req, res) {
      if (req.user.is('admin')) {
        res.render('home/admin');
      } else if (user.can('login')) {
        res.render('home/login');
      } else {
        res.render('home');
      }
    })
    user.can(action) and user.is(action)

Inside the views of an express application you may use userCan and userIs which are equivallent to req.userCan and req.userIs

e.g.

    <% if (userCan('impersonate')) { %>
      <button id="impersonate">Impersonate</button>
    <% } %>

or in jade:

    if userCan('impersonate')
      button#impersonate Impersonate

**Comment by jimmyhchan** [comment]
Helpers need to return a chunk. Check out https://github.com/linkedin/dustjs-helpers/blob/master/lib/dust-helpers.js#L190 the first helper for an example.  You allow the main section (between the helper opening tag and :else) to render by `return bodies.block(chunk, context);`. You allow the alternate section (between :else and end tag) by `return bodies.else(chunk, context);`


* I highly recommend you do NOT do authorization/authentication of user permissions on client since this is so easy to get around.
* Please use StackOverflow for questions.

**Comment by finfort** [comment]
Thank you @jimmyhchan  for your answer, i didn't do my authorization/authentication on a client it's just for getting html template clean, and also i already protect routes on server 
Already asked here http://stackoverflow.com/q/34638580/880709  but no luck for now. Big thanks to @interrobang

**Comment by sethkinast** [comment]
No need to crosspost; the same people read StackOverflow that read the issue tracker (and a lot more people read StackOverflow)
