### ISSUE TITLE
AMD format not properly implemented

### ISSUE THREAD

**Issue by gajewsk2** [linkedin/dustjs#717]
According to this issue: #https://github.com/systemjs/systemjs/issues/1096, the implementation is using define twice which breaks AMD standards and SystemJS AMD module compatibility.

**Comment by sethkinast** [comment]
Thanks, will take a look. This does seem to work properly with require.js
which is the only loader that we have tests for currently, so I guess just
an implementation detail.

**Comment by sethkinast** [comment]
Briefly, this is a lot trickier than it might appear. Dust is split into several pieces that you might include. There's the core, which is all you need to render precompiled templates. There's the compiler, which is heavy enough that we include it in a separate module (but during build time we combine them-- this is important). Then there are the Dust helpers, which you need to be able to require separately AND they need to know how to require a copy of Dust to inject themselves into.

So the current situation is:

Dust core registers itself as a named module `dust.core`.
Compiler registers as `dust.compiler` and requires `dust.core`.
Helpers require `dust.core`.

For proper AMD goodness we want to export an anonymous module so that you can require Dust and it works without having to know magic names like `dust.core`. So during the Dust build step, we build two files:

`dust-core.js` copies in the `dust.core` named module, and appends an anonymous module that sets up AMD template loading. This is the module that you load when you `require('dist/dust-core')` and it follows the require.js optimizer pattern to my understanding (multiple named modules in a file, one anonymous module as entry point).

`dust-full.js` concats the `dust.core` and `dust.compiler` named modules. Notice that `dust.compiler` can find `dust.core` because it's already been registered in the same file, by a name-- this prevents the compiler from having to know anything about paths or filenames and makes sure that everything works in any environment. Then, the same anonymous module from above (but with the compiler attached to the Dust object as well) is exported for you to require.

The Dust helpers then make use of the fact that Dust has been registered under a name to do the same thing as the compiler-- even though they're a separate package altogether. This is similar to the reason that jQuery registers itself as a named module-- jQuery plugins need to know they can require 'jquery' rather than having to use some special path.

So there is no good way to my knowledge (and I did spend quite a bit of time hashing out this solution back in Dust 2.5) to allow Dust to work both so universally, as a global, CJS, and AMD module, and yet operate across multiple files like this.

However, I see this issue https://github.com/systemjs/builder/issues/337 and that, combined with the fact that require.js handles this case fine, makes me think that this is either a part of the spec that is unclear or loosely defined-- I think Dust isn't doing anything wrong here.

I'm going to whip up an example using the workaround posted in that issue; let's see if that works for you.

**Comment by sethkinast** [comment]
The workaround works, but then the require.js optimizer breaks since it can't detect the aliased define. I am starting to think this is a SystemJS feature gap, but would be happy to be told otherwise.

**Comment by gajewsk2** [comment]
@guybedford

**Comment by guybedford** [comment]
A few issues are coming up along these lines. I've posted https://github.com/systemjs/systemjs/issues/1108 to track further in SystemJS support.

It's hairy territory though sharing a registry with provided names as it's just opening the door to name collissions and is not a good idea at all, but we may be able to get it to work. I wouldn't hold my breath for a SystemJS fix very soon.

**Comment by sethkinast** [comment]
@gajewsk2 I can help you with the workaround patch if you'd like to work with SystemJS.

@guybedford thanks for taking a look. I don't really enjoy the current solution we have but it's the only thing that seems to work to allow our dependents to require Dust by name instead of by path, while also allowing Dust consumers to require Dust by path.

I've looked into just overhauling our build pipeline entirely but there are filesize tradeoffs to building Dust as modules and smashing them together using webpack or such.

**Comment by sethkinast** [comment]
@guybedford I'm also totally open to reworking the format in which we define the submodules if it can make your life easier. My expertise does not lie in module systems :P I just have never found another way for this to work properly.

**Comment by guybedford** [comment]
@sethkinast the workaround jspm config would probably be best for now, simply telling jspm to treat dustjs as a global or CommonJS module to avoid these issues. Thanks for offering, but there's no need to rework AMD, this is about compatibility. I think we can support this and it has come up before, so I'm tracking the feature in https://github.com/systemjs/systemjs/issues/1116, it just will take some time.

**Comment by guybedford** [comment]
I did get around to implementing this actually, so this should work with the latest SystemJS Builder 0.15.10.
