### ISSUE TITLE
EscapeHtml and EscapeJs for Array objects

### ISSUE THREAD

**Issue by ikkisoft** [linkedin/dustjs#741]
As demonstrated by [this bog post](https://artsploit.blogspot.se/2016/08/pprce2.html), the escape functions in Dust can be bypassed by using an array object, instead of string.

https://github.com/linkedin/dustjs/blob/c20e70edb2041a66067a010bdefbf9fe3267c7ab/lib/dust.js#L846

We should probably iterate through the objects and sanitize all nested strings.

**Comment by sethkinast** [comment]
Hey,

That's a nice blog post! I think the main issue here is that they're passing unsanitized query params to eval-- Dust is not trying to sanitize Javascript for evaling; it's only concerned with sanitizing them for output to a string. The mistake by the PayPal devs is that they allowed arbitrary content into that query param instead of vetting it.

I think the exact issue on the blog would be solved by this commit though, https://github.com/linkedin/dustjs/pull/534/files

**Comment by sethkinast** [comment]
Here's the same function in the latest Dust: https://github.com/linkedin/dustjs/blob/master/lib/dust.js#L1094

**Comment by sethkinast** [comment]
And that is definitely one of the reasons that we removed `@if` entirely, eval may be convenient and clever but it has no place in template code...

**Comment by ikkisoft** [comment]
Totally agree with you on the specific case, but we should also build frameworks that are resilient to potential attacks (as much as we can)

It looks like the latest version of dust.js is already fixed, thus we can probably close this issue. Thanks!

**Comment by sethkinast** [comment]
Yep totally in agreement that the if helper impl was flawed. We definitely
should avoid user footguns when possible.

Thanks again for the report!
