### ISSUE TITLE
{?exists/} behavior different when using promises

### ISSUE THREAD

**Issue by samuelms1** [linkedin/dustjs#752]
My team noticed recently that the {?exists/} behavior is different when promises.  The only difference we've seen so far is that if you provide an empty array to an {?exists/} block that it will skip over the logic inside unless you are using promises in which case an empty array provided to an {?exists/} block will still cause the content inside to render.  If you know this behavior then a work around is simple, but it'd be preferable to have consistent behavior whether or not we are using promises.

I made a [jsfiddle](https://jsfiddle.net/j3h6uder/2/) to demonstrate both an {?exists/} block with an empty array and an {?exists/} block with an empty array provided by a promise.  Both of these should yield the same result but they do not :(

![image](https://cloud.githubusercontent.com/assets/8550267/20064148/f3741f70-a4c6-11e6-9b3c-59543e8343b7.png)

**Comment by sethkinast** [comment]
Thanks for the nice repro case. This is somewhat similar to the `?exists` behavior for context helpers, in which the helper itself isn't evaluated for truthiness, but its very existence makes it truthy-- even if the context helper returned something falsy like an empty array.

@jchan @smfoote what do you think? I can definitely see the value of being able to test the true value of the Promise immediately instead of having to `{#promise}{?.}yes{/.}{/promise}` but is there value in just checking for the existence of the Promise itself?

**Comment by sethkinast** [comment]
Thinking about it a little more, a Promise doesn't have the side effects a context helper may have so evaluating it earlier just changes where we wait for resolution. I think I'm in favor of making this change.

**Comment by samuelms1** [comment]
I made a pull request to resolve the issue:  https://github.com/linkedin/dustjs/pull/753.  I'm not very familiar with the code in the repo, but I think this resolves things nicely.  Either way, thanks for looking into things!

**Comment by samuelms1** [comment]
@sethkinast are you planning a release soon?  I'd like to get this fix via npm

**Comment by sethkinast** [comment]
Yes there should be a 2.8.0 soon, see #757
